---
  - name: Set AMQ Artifact Facts
    set_fact:
      jboss_amq_artifact_tmp_dest: "{{ '/tmp/' + jboss_amq_artifact_name }}"

  - name: Check Existence of AMQ
    stat:
      path: "{{ jboss_amq_install_home }}"
    register: jboss_amq_exists

  - name: Copy JBoss AMQ
    copy:
      src: "{{ jboss_amq_artifact_name }}"
      dest: "{{ jboss_amq_artifact_tmp_dest }}"
    when: transfer_method == 'copy-from-controller' and jboss_amq_exists.stat.exists == false

  - name: Async Download JBoss AMQ from Red Hat Customer Portal
    redhat_csp_download:
      url: "{{ jboss_amq_artifact_source }}"
      dest: "{{ jboss_amq_artifact_tmp_dest }}"
      username: "{{ rhn_username }}"
      password: "{{ rhn_password }}"
    async: 7200
    poll: 0
    register: jboss_amq_download
    when: transfer_method == 'csp-to-host' and jboss_amq_exists.stat.exists == false

  - name: 'Check On JBoss AMQ Download Completion'
    async_status: jid={{ jboss_amq_download.ansible_job_id }}
    register: job_result3
    until: job_result3.finished
    retries: 600
    delay: 10
    when: transfer_method == 'csp-to-host' and jboss_amq_exists.stat.exists == false

  - name: Create AMQ User
    user:
      name: "{{ jboss_amq_user }}"
      comment: "AMQ service account"
      createhome: no
      system: yes

  - name: Create AMQ Base Directory
    file:
      path: "{{ jboss_amq_install_base }}"
      state: directory
      owner: "{{ jboss_amq_user }}"
      group: "{{ jboss_amq_user }}"

  - name: Extract AMQ Archive
    unarchive:
      src: "{{ jboss_amq_artifact_tmp_dest }}"
      dest: "{{ jboss_amq_install_base }}"
      copy: no
      owner: "{{ jboss_amq_user }}"
      group: "{{ jboss_amq_user }}"
    when: jboss_amq_exists.stat.exists == false

  - name: Create AMQ Broker Directory
    file:
      path: "{{ jboss_amq_broker_home }}"
      state: directory
      owner: "{{ jboss_amq_user }}"
      group: "{{ jboss_amq_user }}"

  - name: Create Brokers
    include_tasks: broker_create.yml
    with_items: "{{ amq_brokers | default([]) }}"
