---


- name: install - ensure AMQ install directory exists
  file:
    path: "{{ amq_install_dir | dirname }}"
    state: directory
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
  become_user: root

- name: install - check Existence of AMQ
  stat:
    path: "{{ amq_install_dir }}"
  register: jboss_amq_exists

- name: install - install AMQ
  unarchive:
    src: "{{ amq_distribution }}"
    dest: "{{ amq_install_dir | dirname }}"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
    creates: "{{ amq_install_dir }}"
    remote_src: "{{ amq_remote_src | default('no') }}"
