---

- name: install - install packages
  yum:
    name: "{{ item }}"
  with_items:
    - libaio
  become_user: root
  become: true

- name: Set AMQ Artifact Facts
  set_fact:
    jboss_amq_artifact_tmp_dest: "{{ '/tmp/' + jboss_amq_artifact_name }}"

- name: install - create AMQ platform group
  group:
    name: "{{ amq_group }}"
    state: present
  become_user: root
  become: true

- name: install - create AMQ platform user
  user:
    name: "{{ amq_user }}"
    group: "{{ amq_group }}"
    state: present
  become_user: root
  become: true

- name: install - check Existence of AMQ
  stat:
    path: "{{ amq_install_dir }}"
  register: jboss_amq_exists
