---

- name: configure - clustering - ensure shared storage directory exists
  file:
    path: "{{ amq_broker_data_dir }}"
    owner: "{{ amq_user }}"
    group: "{{ amq_group }}"
    state: directory
  become_user: root
  become: true
